### ISSUE TITLE
Empty Date for NMEA importing tracks

### ISSUE THREAD

**Issue by es-ak** [wolfgang-ch/mytourbook#1]
Hello, 
MyTourbook version Version: 15.6.0

I faced with error with Date set when importing track in NMEA format. All tracks imported from NMEA files has current Date.

After detailed investigation I found an issue in `org.opengts.util-MT-2015-02-23.jar` library that used for NMEA data parsing.
There are filled with zeroes Date value when NMEA string started with `$GPGGA` sentence, nevertheless it is calculated before.

Proposed workaround in: `net.tourbook.device.nmea.NmeaDataReader.parseNMEAStrings(final ArrayList<String> nmeaStrings)`

    long ddmmyy = 0L;
    // parse all nmea lines
    for (final String nmeaLine : nmeaStrings)
    {
        nmea.parse(nmeaLine);
        if (nmeaLine.startsWith("$GPRMC") || nmeaLine.startsWith("$GPVTG"))
        {
            ddmmyy = nmea.getDDMMYY(); // mandatory for these lines
        }
    }
    // XXX workaround
    nmea.setDDMMYY(ddmmyy);

Thank you, Alexey.

**Comment by wolfgang-ch** [comment]
merged your code
