### ISSUE TITLE
endless loop when reading a CM4xxM DAT file

### ISSUE THREAD

**Issue by cyc1ingsir** [wolfgang-ch/mytourbook#125]
Hi,
the last file, I saved from my CicloSport CM414AM includes another very unlikely data constellation :-). Similar to this one:
https://github.com/wolfgang-ch/mytourbook/blob/53502fb8156f24da8449c75929090261210dd4b4/bundles/net.tourbook.device/src/net/tourbook/device/cm4xxm/CM4XXMDeviceReader.java#L536

The DD pointer discovered after the last tour in this case however, doesn't point to the initial AA record but to the one of the second tour.
I implemented a fix for this but the PR isn't quite ready yet.
Basically it is based on an implementation of an ancient project of mine:
https://gitlab.com/cyc1ingsir/openhac/blob/master/src/main/cm414tourlistfactory.cpp#L146

Even though the dangling DD pointer (in this case) points to a valid AA record by chance, 
the referenced AA record points to a different DD record. 
Hence, the DD record discovered is not a valid one.
A DD record may be validated by verifying the consistency of the backward as well as the forward reference:

``` java
        /*
	 * Verify that a DD record not only points to an AA record, 
	 * but the AA record pointed to, also references the same DD record.
	 * In case, it doesn't, a dangling / left over / invalid DD pointer was discovered.
	 * Even though, this is quite unlikely, it has happened before.
	 */
	private boolean verifyReferenceConsitency(final RandomAccessFile file, int offsetDDRecord) throws IOException {
		final byte[] buffer = new byte[5];
		String recordType = UI.EMPTY_STRING;
		
		file.seek(offsetDDRecord);
		file.read(buffer);
		recordType = new String(buffer, 2, 2);

		// make sure we read a DD record
		if (!recordType.equalsIgnoreCase("DD")) { //$NON-NLS-1$
			log.debug("No DD record found!");
			return false;
		}

		int offsetAARecord = DataUtil.readFileOffset(file, buffer);
		file.seek(offsetAARecord);
		file.read(buffer);
		recordType = new String(buffer, 2, 2);
		// make sure we read a DD record
		if (!recordType.equalsIgnoreCase("AA")) { //$NON-NLS-1$
			log.debug("No AA record found!");
			return false;
		}
		
		int forwardReference = DataUtil.readFileOffset(file, buffer);
		if (forwardReference != offsetDDRecord) {
			log.debug("DD -> AA -> DD record references not constistent!");
			return false;
		}
					
		return true;
	}
```

This could be called from within the while loop, just before the other check referenced above
``` java
if (!verifyReferenceConsitency(fileRawData, offsetDDRecord)) {
    break;
}
```
This fixes the problem for me.
In case you think, it's a valid fix, I could  craft a PR. 
I can provide my DAT file for testing but would prefer to send it via mail.

**Comment by wolfgang-ch** [comment]
I can include this fix.

When you send your email address to me with https://sourceforge.net/u/wolfgang-ch/profile/ then I will send you my email address
