### ISSUE TITLE
Renamed 2 Plugins

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#13]
# Important Info

After this commit https://github.com/wolfgang-ch/mytourbook/commit/3801169f6ff85e64b8d147ae21f5eb4e5d9c648a and you will merge the master branch into your branch, please read this info:

## 2 Plugins are renamed and need to be selected in the app launcher

**Very Important**
net.tourbook.ext.apache contains the newest versions of derby/lucene. When you run MT with this plugin, the **tour database cannot be opened anymore with an older version!!**

For development I **never** use my "production" tour database, I created a batch file to easily copy my "production" tour database into my dev environment.

### Old plugins

![mt-plugin-old](https://user-images.githubusercontent.com/1283445/47952149-48c27b80-df6b-11e8-89e1-3e755e2e28d2.png)

### Renamed plugins

![mt-plugin-new](https://user-images.githubusercontent.com/1283445/47952228-4ca2cd80-df6c-11e8-8b6a-da81a41f7a44.png)

## Cleanup

To run the app successfully again in the IDE, you may need to cleanup the plugins. I needed 2 or 3 tries to finally run it.

![mt-clean-projects](https://user-images.githubusercontent.com/1283445/47952301-61cc2c00-df6d-11e8-9d93-d60a82905db5.png)

**Comment by telemaxx** [comment]
i dont see apache and geoclipse. i have made a "merge" before

![grafik](https://user-images.githubusercontent.com/22706487/48660843-dc667280-ea68-11e8-9e18-d1725095783c.png)

i don't find this "clean" window in you're last screenshot. is this different than run configuration?

**Comment by wolfgang-ch** [comment]
> i dont see apache and geoclipse

First you need to import the 2 renames plugins into the workspace, before they appear in the workspace plugin list.

>i don't find this "clean" window in you're last screenshot. is this different than run configuration?

You can find "clean" in the main menu Project/Clean

**Comment by telemaxx** [comment]
thanks, now its working.

**Comment by wolfgang-ch** [comment]
18.13 is released
