### ISSUE TITLE
Average elevation change

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#145]
The value for average elevation change is set for newly imported tours but for existing tours there is no simple feature to set it -> Tour Book view shows empty values for individual tours

https://github.com/wolfgang-ch/mytourbook/blob/612f94c25f0939bb8f3a3fc22585968ca4e9f5cc/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L359-L362

**Comment by wolfgang-ch** [comment]
`ActionComputeElevationGain` do not set `avgAltitudeChange`

https://github.com/wolfgang-ch/mytourbook/blob/aa770b578ca15bbc22c30b7f4b103dbbbd2d381c/bundles/net.tourbook/src/net/tourbook/ui/action/ActionComputeElevationGain.java#L126-L141

**Comment by FJBDev** [comment]
Because elevation change value is based on gain and loss, I decided to recompute it every time the elevation gain and loss are recomputed
See [here](https://github.com/wolfgang-ch/mytourbook/blob/612f94c25f0939bb8f3a3fc22585968ca4e9f5cc/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L9484)

I assumed that if a user wanted to compute elevation change for existing tours, they could recompute elevation gain from the Preference Menu and without changing the Peucker tolerance menu, the gain values would remain unchanged but the elevation change values would be computed.
Do you think I should create a menu in the preferences to recompute ALL elevation change values instead ?

**Comment by FJBDev** [comment]
> The value for average elevation change is set for newly imported tours but for existing tours there is no simple feature to set it -> Tour Book view shows empty values for individual tours
> 
> https://github.com/wolfgang-ch/mytourbook/blob/612f94c25f0939bb8f3a3fc22585968ca4e9f5cc/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L359-L362

Fixed. See my PR.

However, I also fixed something you seem to have forgotten : 

Also, why do you use an array if it's to use only 1 value ? Wouldn't it be better to use a simple int variable as below ?
```
 final int elevationOld = 0;
 final int elevationNew = 0;
```

**Comment by wolfgang-ch** [comment]
> However, I also fixed something you seem to have forgotten in your commit 

This can happen :-)

```
final int elevationOld = 0;
final int elevationNew = 0;
```
A variable must be `final` that it can be set outside of a runnable. So this is the trick to change simple integer values within a runnable, in your code you could not modify a final integer value.

**Comment by wolfgang-ch** [comment]
> I assumed that if a user wanted to compute elevation change for existing tours, they could recompute elevation gain from the Preference Menu and without changing the Peucker tolerance menu, the gain values would remain unchanged but the elevation change values would be computed.
> Do you think I should create a menu in the preferences to recompute ALL elevation change values instead ?

Your current solution is now OK

**Comment by FJBDev** [comment]
> at it can be set outside of a r



> > However, I also fixed something you seem to have forgotten in your commit
> 
> This can happen :-)
> 
> ```
> final int elevationOld = 0;
> final int elevationNew = 0;
> ```
> 
> A variable must be `final` that it can be set outside of a runnable. So this is the trick to change simple integer values within a runnable, in your code you could not modify a final integer value.

Oh ok, thanks for the explanation.
