### ISSUE TITLE
Changed text value

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#146]
@FJBDev 
I improved the displayed text by showing also the selected delimiter value, the french translation do not yet show this change.

The text key and the original text value was also modified. The original text was shortend similar to eclipse https://www.eclipse.org/eclipse/news/4.13/platform.php#shorter-dialog-texts

https://github.com/wolfgang-ch/mytourbook/blob/33ebc2a6fbed6d77d40d76a7cd7e3c2acbd3066f/bundles/net.tourbook/src/net/tourbook/ui/action/ActionComputeCadenceZonesTimes.java#L71-L74

**Comment by FJBDev** [comment]
I will update the french text.

**Comment by FJBDev** [comment]
See my [PR](https://github.com/wolfgang-ch/mytourbook/pull/147)
