### ISSUE TITLE
FYI: Line breaks in release notes

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#152]
@FJBDev

 **FYI**

In the release notes you should not enter line breaks within a paragraph as I have to delete them when updating the webpage.

https://github.com/wolfgang-ch/mytourbook/blob/9ab1f8e2f8d4a7efed297d74eef9d848bd02bf4c/info/release-notes/19.10.0-readme.txt#L73-L78

![line breaks in release notes](https://user-images.githubusercontent.com/1283445/67140390-43347300-f25a-11e9-94c1-d7d0620d3676.png)

**Comment by FJBDev** [comment]
I fixed it. See my [PR](https://github.com/wolfgang-ch/mytourbook/pull/153/)
