### ISSUE TITLE
Broken OSM tiles in offline maps

### ISSUE THREAD

**Issue by dgoltzsche** [wolfgang-ch/mytourbook#168]
Hi!

When turning on offline maps for the 2D map, all PNG files saved in `.mytourbook/offline-map2/osm/` contain seemingly random data, but have a correct PNG header. The tiles are first displayed correctly on the map, but when zooming or restarting mytourbook, the whole saved map looks like random data.

I'm using v19.10.0

These are two example of the saved tiles for two zoom levels:
![361](https://user-images.githubusercontent.com/3463439/72593225-bf476100-3904-11ea-9dfa-560a01949c74.png)
![675](https://user-images.githubusercontent.com/3463439/72593488-62987600-3905-11ea-8ddf-6ed27a9c305f.png)

**Comment by FJBDev** [comment]
@dgoltzsche 
This is a know bug in the SWT library that I have reported [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=553240) and that I have fixed in the next version of MyTourbook by updating to SWT 4.14
