### ISSUE TITLE
Feature: Export map to vector graphic (SVG)

### ISSUE THREAD

**Issue by DirkSchmitt** [wolfgang-ch/mytourbook#174]
Feature Request
-----------------------
The map window with track and other informations should be exported (as displayed) to a vector graphic (SVG) .

Use Case
--------------
I have the use case that during the travel of several weeks/months I take notes in mytourbook. After the tour I'm writing a more detailed diary.

For this diary I currently create screen hardcopies of the map window.
To get a printable quality I require a big monitor (32"). The results on the notebook (11") are not sufficient.

**Comment by telemaxx** [comment]
Hi Dirk,
i think exporting as SVG would not help you.
the maps data are bitmaps from some tileserver.
so inside the svg there would also be just this bitmaps.

Wouldnt it be better storing [map- bookmarks](http://mytourbook.sourceforge.net/mytourbook/index.php/documentation/tools/map-bookmark)?

Map Bookmarks are storing the map position, zoom etc.

**Comment by DirkSchmitt** [comment]
The goal is to produce an image of a 2D-Map (or maybe also 3D-Map) for including in a print documentation of a bicycle Journey (e.g. Jakobsweg / Camino).

Best choice is a vector graphic, 2nd choice is a high resolution png. 
As I see the *tiles* have the resolution 300x300PPI.

It would be great if an *exported* 2D-Map can preserve this resolution from the source instead my current workflow using screenshots.

**Comment by FJBDev** [comment]
@DirkSchmitt 
I have added, in the next release of MT, 2 options in the 2D Map contextual menu to export the 2D map view :

![image](https://user-images.githubusercontent.com/25235665/105883278-e7f84100-5fc3-11eb-898d-53f3c864395a.png)


- to an image file

![image](https://user-images.githubusercontent.com/25235665/105883337-f9d9e400-5fc3-11eb-805d-3ff7a06e6abd.png)


- to the clipboard
![image](https://user-images.githubusercontent.com/25235665/105883484-242ba180-5fc4-11eb-8f84-f6a53f95dbb6.png)


Frederic

**Comment by wolfgang-ch** [comment]
Export as SVG is out of scope for MT but a map can be exported as image
