### ISSUE TITLE
Photos actions in 2.5D map are not in sync

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#213]
It can happen that the show photo action in the toolbar is not in sync with the photo layer checkbox.

I already enabled the show photo action only when photos are available https://github.com/wolfgang-ch/mytourbook/commit/03907b4858558acfff71485f69dbd0f39351cc20  but have not yet synched it with the photo layer state.

![map25-photo-sync](https://user-images.githubusercontent.com/1283445/89118146-a3bc3600-d4a3-11ea-81a9-3e601b19a78c.png)

**Comment by telemaxx** [comment]
The photo layer checkbox "Photo with title" should only switch the phototitle on/off, not the whole layer.
if you remember, my first implementation was a checkbox inside the map2.5d preferences.
best position for this checkbox would be a option i one of youre famous slideouts, but that is to complicate for me.

**Comment by telemaxx** [comment]
commit https://github.com/wolfgang-ch/mytourbook/commit/03907b4858558acfff71485f69dbd0f39351cc20 is a good idea.

**Comment by wolfgang-ch** [comment]
> The photo layer checkbox "Photo with title" should only switch the phototitle on/off, not the whole layer.
> if you remember, my first implementation was a checkbox inside the map2.5d preferences.
> best position for this checkbox would be an option in one of youre famous slideouts, but that is to complicate for me.

For 20.8 it is OK, I just fixed a much more important issue https://github.com/wolfgang-ch/mytourbook/commit/d3e09e3afe3c2b6d439ebd9c85afe1603eeb909b
