### ISSUE TITLE
TourTag Filter causes SQL error when using "No Category" view on Tour Book

### ISSUE THREAD

**Issue by rtdog** [wolfgang-ch/mytourbook#220]
I suspect you know this @wolfgang-ch , but if you use the Tour Tag filter and have the new "No Category" view layout selected on the "Tour Book" view, then you get a SQL error because the tag ID isn't in the table.

![2020-08-12_8-28-40](https://user-images.githubusercontent.com/7549821/90014957-df11ee00-dc75-11ea-83a2-0190fff5357b.png)

**Comment by FJBDev** [comment]
Nice find @rtdog . Is that a regression that appeared in 20.8 ? or has it been present for several versions already ?

**Comment by wolfgang-ch** [comment]
I've never seen this error otherwise I've fixed it. The new flat tour book view can be the reason that there are still some issues. Tags are not yet displayed in the flat view, this needs to be implemented.

**Comment by wolfgang-ch** [comment]
fixed

![mt-flat-view-with-tag-filter](https://user-images.githubusercontent.com/1283445/91186304-2f199780-e6ef-11ea-96ba-18234a86591d.png)
