### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by Starmbi** [wolfgang-ch/mytourbook#237]
Hello,

After I modified a gpx file with GPSBabel, MyTourbook was not able to import it.
With the original file I had no problems.
 
When I replaced the line :

`<gpx version="8.2" creator="GPSBabel - https://www.gpsbabel.org" xmlns="http://www.topografix.com/GPX/8/2" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0">`

with the line of the original file:

`<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0" creator="Komoot" version="8.2">`

the import works.

Error log:

Could not read data file 'D:\simple_5m.gpx'java.lang.NullPointerException	at net.tourbook.device.gpx.GPX_SAX_Handler.finalizeTour(GPX_SAX_Handler.java:1044)	at net.tourbook.device.gpx.GPX_SAX_Handler.endElement(GPX_SAX_Handler.java:530)	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)	at javax.xml.parsers.SAXParser.parse(Unknown Source)	at net.tourbook.device.gpx.GPXDeviceDataReader.processDeviceData(GPXDeviceDataReader.java:183)	at net.tourbook.importdata.RawDataManager.importRawData_10(RawDataManager.java:1603)	at net.tourbook.importdata.RawDataManager.access$8(RawDataManager.java:1553)	at net.tourbook.importdata.RawDataManager$5.run(RawDataManager.java:1498)	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:55)	at net.tourbook.importdata.RawDataManager.importRawData(RawDataManager.java:1423)	at net.tourbook.importdata.RawDataManager$7.run(RawDataManager.java:1918)	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by FJBDev** [comment]
Hello @Starmbi 

Can you please specify :
- The version of MyTourbook used
- Attach an example of GPX file for which the issue can be reproduced

My hunch is that the culprit is the topografix namespace added by GPS Babel that is wrong :
` "http://www.topografix.com/GPX/**8/2**"`

This is the value that I would expect knowing the GPS schema : `http://www.topografix.com/GPX/1/1`

Frederic

**Comment by Starmbi** [comment]
Hello @FJBDev 

The version is of MyTourbook is 20.8.0.
I attached a file, that shows the issue.
Please remove the  file extension ".txt" before use it, because Github does not support GPX files.

Yes, ist is a good idea to contact gpsbabel.


Thank you for your help

Stefan 

[simple_5m.gpx.txt](https://github.com/wolfgang-ch/mytourbook/files/5349153/simple_5m.gpx.txt)

**Comment by FJBDev** [comment]
@Starmbi 

Thanks for providing the file example.
After investigation, I have confirmed that my hunch is right and that the Topografix version modified by GPSBabel is wrong.
Hence, updating the topografix namespace as below fixed the import:
![image](https://user-images.githubusercontent.com/25235665/95492138-e133b880-0957-11eb-94ad-378c901489f1.png)

![image](https://user-images.githubusercontent.com/25235665/95492196-f3155b80-0957-11eb-9371-c88b353c9940.png)

And when you look at the Topografix website, the [latest standard](https://www.topografix.com/gpx.asp) is **1.1** and not 8.2

So, I think you should created an issue on the [GPSBabel GitHub](https://github.com/gpsbabel/gpsbabel) instead.

I hope that helps!
Frederic

**Comment by Starmbi** [comment]
Hello,

i contacted _gbsbabel_ an they said, that the weird version is not from _gpsbabel_.
An they are right!

One of the many programs, I used, wrote a version 8.2 into the header. (please scroll right, to see it)
```
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0" creator="Komoot" version="8.2">
```
After I downloaded the original file again and edited it with _gpsbabel_, I was able to import it into _MyTourbook_ without problems.
Please see my conversation with _gpsbabel_ [here](https://github.com/gpsbabel/gpsbabel/issues/644)

Thank you for your effords, issue can be closed.

Sorry
Stefan

**Comment by FJBDev** [comment]
Closing this issue

**Comment by wolfgang-ch** [comment]
Closed on request
