### ISSUE TITLE
Tourmarker re-import could fail

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#240]
The old code do not work for combined reimport data options, when tour markers and other reimport data, e.g. swimming are selected

https://github.com/wolfgang-ch/mytourbook/blob/32465b1a8296571c7a884bf74992398c54072e76/bundles/net.tourbook/src/net/tourbook/importdata/RawDataManager.java#L1340-L1365

**Comment by FJBDev** [comment]
Fixed
