### ISSUE TITLE
[LINUX ONLY] When deleting a tour tag filter/profile filter, the desktop crashes

### ISSUE THREAD

**Issue by FJBDev** [wolfgang-ch/mytourbook#247]
Steps to reproduce :
- Try to delete a tour tag filter/profile filter.... any UI involving the [AdvancedSlideoutShell](https://github.com/wolfgang-ch/mytourbook/blob/47f4a50084ec9b816ba6b32a4d90b7c7deb3856d/bundles/net.tourbook.common/src/net/tourbook/common/tooltip/AdvancedSlideoutShell.java) and calling  `MessageDialog.openConfirm()`

![image](https://user-images.githubusercontent.com/25235665/98698161-fa52cf00-2332-11eb-99c0-5f44f8707e0d.png)

- Desktop crashes and nothing is logged in the desktop log (For Cinnamon 3.8, see the file that stays unchanged : ~/.xsession-errors)

![image](https://user-images.githubusercontent.com/25235665/98697953-bb247e00-2332-11eb-99ff-88aac2215de9.png)

_Issue reproduced on Debian 9.X and 10.X with Cinnamon 3.8 and Gnome 3, MyTourbook 20.3 & 20.8 (didn't test older versions)_

@wolfgang-ch, @telemaxx, @rtdog, @condemnedmeat: are you able to reproduce this issue with your linux ?

**Comment by wolfgang-ch** [comment]
Ubuntu is not crashing when the confirm message dialog is opened but the dialog is not visible, however it could be used with the keyboard, pressing the <space> key will delete the profile (in the above example) and afterwards the UI runs as before, I'll investigate it, seems to be a problem with the shell which is used for the message dialog.

**Comment by wolfgang-ch** [comment]
After many try and errors I found the reason: slideouts are on top of other windows but a default `MessageDialog` in not on top -> it is behind the slideout which I will fix for all slideout default message dialogs

**Comment by FJBDev** [comment]
Thanks, I tried to look myself several days ago in the [AbstractRRShell](https://github.com/wolfgang-ch/mytourbook/blob/47f4a50084ec9b816ba6b32a4d90b7c7deb3856d/bundles/net.tourbook.common/src/net/tourbook/common/tooltip/AbstractRRShell.java) but it was very complicated to understand what the RRShell does (and what does RR stand for?)

**Comment by wolfgang-ch** [comment]
RR -> **R**eparented **R**esize Shell https://github.com/wolfgang-ch/mytourbook/blob/47f4a50084ec9b816ba6b32a4d90b7c7deb3856d/bundles/net.tourbook.common/src/net/tourbook/common/tooltip/AbstractRRShell.java#L34

When you hover with the mouse over a tooltip, it gets reparented (shell content is reparented into another shell) to make it resizeable -> very complicated stuff

**Comment by FJBDev** [comment]
@wolfgang-ch I confirm that [your commit](https://github.com/wolfgang-ch/mytourbook/commit/4f7af6908b1be9bd61bcd086facfb241cbcdb265) fixed it.
You can close this issue

**Comment by FJBDev** [comment]
I found the same exact issue when trying to modify the 3D map track color and open the menu:

![image](https://user-images.githubusercontent.com/25235665/114796029-2a245980-9d4d-11eb-97f6-2c797ba6124a.png)

![image](https://user-images.githubusercontent.com/25235665/114796069-3ad4cf80-9d4d-11eb-8c7f-c8d5321205ac.png)

**Comment by wolfgang-ch** [comment]
Ubuntu 20.04 do not crash, however the dialog is behind the slidout but it can be moved to be fully visible. When setting the dialog style also to `SWT.ON_TOP` then the dialog cannot be moved. I also checked the parent shell and it is OK, it is the slidout.

![mt map3 track color dialog](https://user-images.githubusercontent.com/1283445/114882063-d9236c80-9e03-11eb-9553-686e8c0cf3e6.png)

**Comment by FJBDev** [comment]
> Ubuntu 20.04 do not crash

My hunch is that the Linux distro doesn't matter in that issue but it is the desktop used. Are you using Gnome 3 ? I am using [Cinnamon](https://en.wikipedia.org/wiki/Cinnamon_(desktop_environment))

**Comment by wolfgang-ch** [comment]
This is my ubuntu version

![my ubuntu](https://user-images.githubusercontent.com/1283445/114972309-92268d00-9e7e-11eb-943f-7795d2c5747d.png)

**Comment by FJBDev** [comment]
Yep, Gnome 3

**Comment by telemaxx** [comment]
i can confirm that behavior with cinnamon.
default was cinnamon:
![grafik](https://user-images.githubusercontent.com/22706487/115066498-e9b11100-9eef-11eb-8118-8c51602bc542.png)

for the test i also installed mate:
`sudo apt install mint-meta-mate`

now i can switch in the login window between both.
![grafik](https://user-images.githubusercontent.com/22706487/115066457-d7cf6e00-9eef-11eb-8558-84e99f9acdd5.png)

with mate i can set the track color(window is behind slideout)

with cinnamon i got the same error as Frederic
