### ISSUE TITLE
Uppercase method names

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#254]
I just discovered that the uppercase issues in my first review https://github.com/wolfgang-ch/mytourbook/pull/252#pullrequestreview-539329668 were not adressed in the last https://github.com/wolfgang-ch/mytourbook/pull/253

https://github.com/wolfgang-ch/mytourbook/blob/b3bad279c4de5804ad65a46121488ceca2346df1/bundles/net.tourbook.tests/test/utils/Comparison.java#L55-L57

**Comment by FJBDev** [comment]
My apologies, I forgot about that one. I will fix tomorrow

**Comment by FJBDev** [comment]
Fixed in my [PR](https://github.com/wolfgang-ch/mytourbook/pull/255)
