### ISSUE TITLE
Strava guidelines

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#315]
https://github.com/wolfgang-ch/mytourbook/blob/88517696a9c28d898bba123955dbbe3ad4dc8ad0/info/release-notes/21.3.0-readme.txt#L17-L22

@FJBDev Do you think we comply with Strava guidelines with this webpage?

![mt-cloud](https://user-images.githubusercontent.com/1283445/110817971-1dfc3680-828d-11eb-8c57-8a0336656d1f.png)

**Comment by FJBDev** [comment]
> 
> 
> https://github.com/wolfgang-ch/mytourbook/blob/88517696a9c28d898bba123955dbbe3ad4dc8ad0/info/release-notes/21.3.0-readme.txt#L17-L22
> 
> @FJBDev Do you think we comply with Strava guidelines with this webpage?

That looks good to me considering their [guidelines](https://developers.strava.com/guidelines/)

However, I see those issues:
- Typo missing a "o"
![image](https://user-images.githubusercontent.com/25235665/110829791-c0002c80-8255-11eb-815b-09a28c10af5f.png)
- Suunto
I would use a better logo than the one used in MT.
[Here ](https://img.materialbank.net/NiboWEB/suunto/showCartPublicContent.do?uuid=3484780&random=816898&lang=en)is the link where you can download the official logos
You might want to take one in the "Suunto Compatible logos" folder

![image](https://user-images.githubusercontent.com/25235665/110830025-035a9b00-8256-11eb-8432-58067b9af782.png)

**Comment by FJBDev** [comment]
Also, I see this
![image](https://user-images.githubusercontent.com/25235665/110830320-516f9e80-8256-11eb-92a3-29b3780fe7f6.png)

MT doesn't support (yet?) the upload of tours, only the download through the Easy Import Manager

**Comment by wolfgang-ch** [comment]
All Fixed

![mt-cloud](https://user-images.githubusercontent.com/1283445/110963202-15b9ff00-8352-11eb-85ac-b91d071b0f99.png)
