### ISSUE TITLE
Display all R-R Values in the Tour Chart

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#318]
One timeslice can contain multiple (>100) R-R values which are not displayed in the tour chart

![mt rr gaps](https://user-images.githubusercontent.com/1283445/113165779-7bf3bc80-9242-11eb-94d8-a63bc3332c2b.png)

**Comment by wolfgang-ch** [comment]
Finally, after some days and many try and errors, could find a not very complicated algorithm to sync 3 different data series

![mt fixed rr gaps](https://user-images.githubusercontent.com/1283445/113482318-86aa8d80-949e-11eb-999b-780a7f82becc.png)


I did some drawings which also helped

![sync 3 time series](https://user-images.githubusercontent.com/1283445/113482343-a80b7980-949e-11eb-80e7-ef3478836999.JPG)



https://github.com/wolfgang-ch/mytourbook/blob/1563a690234a1bb1e411f224be82665b35de8306/bundles/net.tourbook/src/net/tourbook/tour/TourManager.java#L4196-L4288

**Comment by wolfgang-ch** [comment]
Example for a R-R issue:

Time slice 9951 contains a R-R time of 15.600 sec but the time slice is only 1 sec

![mt rr issues](https://user-images.githubusercontent.com/1283445/114052338-40826f00-988e-11eb-9148-3fad7e59e0fe.png)

**Comment by wolfgang-ch** [comment]
The above issue is fixed ...

![mt rr fix 1](https://user-images.githubusercontent.com/1283445/114192896-4b9cd400-994e-11eb-8de1-f9db27a2df38.png)


... but there were other issues

When R-R time is too large, then it is set to the x-axis time, this is visible by a horizontal line to a smaller x-axis value

![mt rr fix 3](https://user-images.githubusercontent.com/1283445/114192989-61aa9480-994e-11eb-8cac-503e0892f756.png)


... and there are other issues, which show obviously wrong R-R values

![mt rr fix 2](https://user-images.githubusercontent.com/1283445/114193570-f44b3380-994e-11eb-85a1-1793b7e045e4.png)

There are 2 different clocks, one in the GPS device and one in the heartbeat device and both time values seems to be not in sync by the provided data.

**Comment by wolfgang-ch** [comment]
Finally, after 3 weeks of testing/implementing, this issue seems now to be fixed, also when
* using distance on the x-axis, this is using the R-R average values and not the R-R intervals -> too complicated and provides propably not very much value
* using heartbeat background color https://github.com/wolfgang-ch/mytourbook/commit/50bc81a5142fe0ecd407a9684150187dc0346f57

**Comment by FJBDev** [comment]
As of 21.3, which format has the import of R-R values supported ? Only the FIT format ?

**Comment by wolfgang-ch** [comment]
> 
> 
> As of 21.3, which format has the import of R-R values supported ? Only the FIT format ?

See "Supported Devices" in https://mytourbook.sourceforge.io/mytourbook/index.php/documentation/tools/heart-rate-variability

**Comment by FJBDev** [comment]
> See "Supported Devices" in https://mytourbook.sourceforge.io/mytourbook/index.php/documentation/tools/heart-rate-variability

Now that you have fixed those issues, I am planning on adding the R-R import for Suunto JSON format.
