### ISSUE TITLE
OS with Dark Theme looks bad together with mytourbook

### ISSUE THREAD

**Issue by DirkSchmitt** [wolfgang-ch/mytourbook#319]
I'm using Linux (Debian), Gnome-Shell with `gtk-theme='DarkMint'
The problem is that the theme settings only used in some parts. 
I'm using  21.03.

![Screenshot](http://user.computer42.org/~dirk/github-attachments/Mytourbook-319.png)

**Comment by FJBDev** [comment]
Did you activate the dark theme in MyTourbook ?

As mentioned in the [20.8 release](https://mytourbook.sourceforge.io/mytourbook/) :

![image](https://user-images.githubusercontent.com/25235665/113356232-7923c500-9331-11eb-9075-d5d8f3f04ae4.png)

**Comment by DirkSchmitt** [comment]
Thanks for the hint.
With `-cssTheme org.eclipse.e4.ui.css.theme.e4_dark` it is usable again with the dark GTK theme.

**Comment by wolfgang-ch** [comment]
> As mentioned in the [20.8 release](https://mytourbook.sourceforge.io/mytourbook/) :

@FJBDev

Every version has a link which you can make visible with this plugin https://addons.mozilla.org/en-US/firefox/addon/display-_anchors/

![mt version links](https://user-images.githubusercontent.com/1283445/113469199-1bd06680-944c-11eb-862d-973c654f3244.png)

**Comment by FJBDev** [comment]
> 
> 
> > As mentioned in the [20.8 release](https://mytourbook.sourceforge.io/mytourbook/) :
> 
> @FJBDev
> 
> Every version has a link which you can make visible with this plugin https://addons.mozilla.org/en-US/firefox/addon/display-_anchors/
> 

Good to know

**Comment by wolfgang-ch** [comment]
In the next version the default themes can be selected in the UI

![mt dark theme pref dialog](https://user-images.githubusercontent.com/1283445/116416021-47235700-a83a-11eb-8ac5-07281cc5d1e1.png)

The W10 dark theme is now also showing more controls in dark mode, e.g. menu, but the MT UI needs a few more tweaks, until all looks good in dark mode

![mt dark theme](https://user-images.githubusercontent.com/1283445/116416334-8a7dc580-a83a-11eb-86d8-5f456c3ffe37.png)

**Comment by wolfgang-ch** [comment]
Chart and statistic are now looking good with the dark theme

![mt dark](https://user-images.githubusercontent.com/1283445/116893447-48d18e00-ac31-11eb-8381-14d1a8b0e619.png)

**Comment by FJBDev** [comment]
> Chart and statistic are now looking good with the dark theme
> 

It is looking good but I notice that it's hard to see the "[night sections](https://github.com/wolfgang-ch/mytourbook/pull/316)" now.

**Comment by wolfgang-ch** [comment]
> 
> 
> > Chart and statistic are now looking good with the dark theme
> 
> It is looking good but I notice that it's hard to see the "[night sections](https://github.com/wolfgang-ch/mytourbook/pull/316)" now.

You may need to draw the night section with a color. 

I have to implement for existing colors a second color for each, one is for the light and one for the dark theme.

**Comment by FJBDev** [comment]
> You may need to draw the night section with a color.
> 
> I have to implement for existing colors a second color for each, one is for the light and one for the dark theme.

Ok, I will do some testing and see which color could be appropriate for the dark theme

**Comment by FJBDev** [comment]
I have chosen this marine blue for the night sections when using the dark theme, thoughts ?

Also, the markers being grey are not really visible but maybe you are working on that at the moment

![image](https://user-images.githubusercontent.com/25235665/117173510-12f3ed00-ad8a-11eb-8bdf-2ecc5f73d205.png)

**Comment by wolfgang-ch** [comment]
>I have chosen this marine blue for the night sections when using the dark theme, thoughts ?

Blue is the color which I also would have choosen for the night section. :-)


>Also, the markers being grey are not really visible but maybe you are working on that at the moment

These are the colors which I thought, when I wrote the above comment https://github.com/wolfgang-ch/mytourbook/issues/319#issuecomment-831680369

**Comment by FJBDev** [comment]
When not using the dark theme, the Easy Import Manager View has always been showing Dark theme for years, is it possible to display the Easy Import Manager in Dark **only** when using the MT dark theme and the rest of the time in **Light** ?

![image](https://user-images.githubusercontent.com/25235665/120016551-fc643e80-bfa1-11eb-8ff4-cf3b061177da.png)

**Comment by wolfgang-ch** [comment]
> 
> 
> When not using the dark theme, the Easy Import Manager View has always been showing Dark theme for years, is it possible to display the Easy Import Manager in Dark **only** when using the MT dark theme and the rest of the time in **Light** ?

It was not planned to support theming for the easy import view and all the photo views. The tour search view is also another view which has currently no theming support.

**Comment by wolfgang-ch** [comment]
When you update to the current main, then all your statistics will be displayed with black color. I just added theming to the tour types :-) Maybe I will set better defaults for the dark tour type colors.

**Comment by wolfgang-ch** [comment]
This issue is fixed in 21.06


![mt-all-2106](https://user-images.githubusercontent.com/1283445/121066739-83978a80-c7ca-11eb-82cf-908a789995a2.png)

**Comment by FJBDev** [comment]
> 
> This issue is fixed in 21.**0**6

You meant 21.6 right ?

**Comment by telemaxx** [comment]
21.6.0

**Comment by wolfgang-ch** [comment]
The last view is now also themed

![image](https://user-images.githubusercontent.com/1283445/121807903-67766c00-cc56-11eb-9b69-a5079fd065bb.png)
