### ISSUE TITLE
Set "Danger Zone" for actions which are performed for ALL tours

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#333]
Similar like in the github admin UI ...

![mt danger zone](https://user-images.githubusercontent.com/1283445/115421096-f8ebd380-a1fb-11eb-97f2-a2868c8888e5.png)

...such operations could also be marked/highlighted in the MT UI

![mt danger zone in UI](https://user-images.githubusercontent.com/1283445/115421099-f9846a00-a1fb-11eb-8a74-be0a97dabc47.png)

...and/or set the foreground color red for the action (radio) text 

@FJBDev What do you think?

**Comment by FJBDev** [comment]
@wolfgang-ch It's a good idea.
Or we can do like in Linux where to use some specific UI, you have to "unlock" first like below to "ungray" some menu:
![image](https://user-images.githubusercontent.com/25235665/115469313-a4dbf180-a1f1-11eb-84e1-4a7c98ca5ad9.png)

So it would look like below and the "All saved tours" would be grayed out and the user can activate/ungray it by clicking on the lock
![image](https://user-images.githubusercontent.com/25235665/115469453-e9678d00-a1f1-11eb-82ea-48941d71b06e.png)

**Comment by wolfgang-ch** [comment]
I like your suggestion, the user not only need to press the unlock button, also the radio button must be selected because this selection should never be saved and resored.

However the user could set the between dates also to include all tours, but then he should be aware of it, or should we display a confirmation dialog when the action is running on more than n tours?

**Comment by telemaxx** [comment]
maybe a question : "Do you really want it, then type YES"
and the user must key in the word in a text box. some program do it this way,  but i don't not remember which. I think partition programs. this avoids don't read and click. 
maybe a hint to backup regularly.

**Comment by FJBDev** [comment]
>some program do it this way, but i don't not remember which

GitHub does. For example, if I try to delete a repo, it will ask me to type the name of the repo

![image](https://user-images.githubusercontent.com/25235665/115603965-0bb6e480-a29e-11eb-875e-f107130cb7f6.png)

**Comment by FJBDev** [comment]
> However the user could set the between dates also to include all tours, but then he should be aware of it, or should we display a confirmation dialog when the action is running on more than n tours?

Maybe we should put this lock that could unlock both radio buttons "All saved tours" and "Between" ??

**Comment by wolfgang-ch** [comment]
> maybe a question : "Do you really want it, then type YES"
> and the user must key in the word in a text box. some program do it this way, but i don't not remember which. I think partition programs. this avoids don't read and click.
> maybe a hint to backup regularly.

I think this is too much, with an unlock button the user have already to select/click the following actions
* Click unlock button
* Select radio button for "all tours" or "between"
* Click delete/re-import button
* Click the confirmation which is always displayed when these options are selected (is just implemented by Frederic)

Except the delete/re-import button, all other actions are not preselected they must be selected explicitly.

There was already a complain that deleting a tour has too many clicks but using the mnemonics with the keyboard, its easier, the same would be here.

**Comment by wolfgang-ch** [comment]
> 
> 
> > However the user could set the between dates also to include all tours, but then he should be aware of it, or should we display a confirmation dialog when the action is running on more than n tours?
> 
> Maybe we should put this lock that could unlock both radio buttons "All saved tours" and "Between" ??

See my above comment to use it also for "Between"

**Comment by FJBDev** [comment]
@wolfgang-ch Do you have a preference for the color of the "lock" image ? I am asking because I know that the icons have a "MT style" and maybe you have a preference to what the "lock" and "unlock" icons should look like before I start drawing them in Inkscape

**Comment by wolfgang-ch** [comment]
What is the "Mt style"?
What I try to do, to reduce number ob lines, without a line, all looks a bit "blurred"
For the color first I would try to use the orange/red color but you have to see it in the context, a color is changed very easily

**Comment by FJBDev** [comment]
Here is what it looks like without bright colors:
![image](https://user-images.githubusercontent.com/25235665/115938804-19649980-a459-11eb-9ca6-d6b774d0ad88.png)
![image](https://user-images.githubusercontent.com/25235665/115938817-22ee0180-a459-11eb-9421-9d61f90a7679.png)

**Comment by wolfgang-ch** [comment]
It looks a bit ugly a button between 2 lines, I think it looks better to have the lock/unlock button for each line separately. They should be in the same "column" but this could be difficult to implement because the radios should have the same parent. Creating the UI is sometimes a little bit experimental when using a more advanced layout.

I also would use a thinner line in the lock image which is also the "MT Style"

**Comment by FJBDev** [comment]
Ok, I will change the UI to have a lock button in each row/line. I will also update my inkscape locks icons to be more "MT style"

**Comment by FJBDev** [comment]
> 
> 
> It looks a bit ugly when a button is located between 2 lines, I think it looks better to have the lock/unlock button for each line separately. They should be in the same "column" but this could be difficult to implement because the radios should have the same parent. Creating the UI is sometimes a little bit experimental when using a more advanced layout.
> 
> I also would use a thinner line in the lock image which is also the "MT Style"

Per your suggestions, does it look better ?:
![image](https://user-images.githubusercontent.com/25235665/116165022-292de900-a6b8-11eb-9a06-adbd92ce20ff.png)

**Comment by wolfgang-ch** [comment]
> 
> 
> > It looks a bit ugly when a button is located between 2 lines, I think it looks better to have the lock/unlock button for each line separately. They should be in the same "column" but this could be difficult to implement because the radios should have the same parent. Creating the UI is sometimes a little bit experimental when using a more advanced layout.
> > I also would use a thinner line in the lock image which is also the "MT Style"
> 
> Per your suggestions, does it look better ?:
> ![image](https://user-images.githubusercontent.com/25235665/116165022-292de900-a6b8-11eb-9a06-adbd92ce20ff.png)

Much :-)

Maybe more horizontal distance of the unlock buttons to the left side, e.g. 10 but this is something you have to test and see how it looks like. I think there is also a gap between "Between" and the 1st date field.

**Comment by FJBDev** [comment]
> Maybe more horizontal distance of the unlock buttons to the left side, e.g. 10 but this is something you have to test and see how it looks like. I think there is also a gap between "Between" and the 1st date field.

I checked but there is no gap in the code between "Between" and the 1st date field.
Maybe I will let you "polish" the UI since you like doing that :-)

Any other UI in MT that is a "Danger zone" where we should use  "lock" ? I can also update that for other menus/UI while I am at it

**Comment by wolfgang-ch** [comment]
> 
> 
> > Maybe more horizontal distance of the unlock buttons to the left side, e.g. 10 but this is something you have to test and see how it looks like. I think there is also a gap between "Between" and the 1st date field.
> 
> I checked but there is no gap in the code between "Between" and the 1st date field.

I checked the code and there is no additional gap, spacing is just from the default settings, except the vertical spacing of the radio buttons


> Maybe I will let you "polish" the UI since you like doing that :-)

I'll do it when I see it


> Any other UI in MT that is a "Danger zone" where we should use "lock" ? I can also update that for other menus/UI while I am at it

I've no critical all tours actions in my mind, there are actions running on all tours but there are no other options to choose from which would be dangerous.

**Comment by wolfgang-ch** [comment]
This feature is implemented

**Comment by FJBDev** [comment]
> This feature is implemented

In 21.6.0 for future readers.
