### ISSUE TITLE
4k Display can create Art

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#356]
![image](https://user-images.githubusercontent.com/1283445/120927155-26270f00-c6e0-11eb-8a0f-d516ecd7032b.png)

**Comment by telemaxx** [comment]
looks like an ink print in the rain

**Comment by FJBDev** [comment]
This is the copy of this painting ? :smile: 
https://www.gerhard-richter.com/en/art/paintings/abstracts/abstracts-19951999-58/abstract-painting-bluered-8273

**Comment by wolfgang-ch** [comment]
> 
> 
> This is the copy of this [painting](https://www.gerhard-richter.com/en/art/paintings/abstracts/abstracts-19951999-58/abstract-painting-bluered-8273) ? 😄

There are some similarities :-)

This is the way how to reproduce it with a 4k display:

- Select a day statistic in the statistic view
- Increase or decrease number of years multiple times

It can happen, that nothing or only the selected tour is displayed. Closing and reopening the view solved this issue.

When the image size in the statistic/chart has not changed since the last painting event, then the same image is reused and this seems to be an issue with the 4k display.

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/wolfgang-ch/mytourbook/commit/203f26fcbee0b68e3a6d0244533e4bd1b40a8121
