### ISSUE TITLE
2D-Map - Legend of Heartrate is capped at 150 bpm

### ISSUE THREAD

**Issue by cyc1ingsir** [wolfgang-ch/mytourbook#362]
Hi Wolfgang et al,
I discovered a minor issue with the newest version:
Vesion: 21.6.0 (Linux)
HeartRates above 150bpm are displayed completely in white and differences between e.g. 153 bpm and e.g 186 bpm are no longer distinguishable on the map.

**Comment by FJBDev** [comment]
@cyc1ingsir 
You are likely using the default capped value of 150

if you go to this menu, you can change the value and even disable the value capping
Preferences :arrow_right: Appearance :arrow_right: Colors :arrow_right: Heartbeat :arrow_right: Mapping color
![image](https://user-images.githubusercontent.com/25235665/123474451-35023280-d5b7-11eb-93cb-6d499092d5f9.png)

I hope that helps!

**Comment by cyc1ingsir** [comment]
Thanks! This helped a lot.
I was looking for a setting like this but had looked for it in the 2D-Map preferences as well as within the athletics heart zone settings without success. So thanks for pointing me into the right direction.

**Comment by wolfgang-ch** [comment]
The track color adjustment can also be activated from the context menu

![image](https://user-images.githubusercontent.com/1283445/123533523-8a088a80-d716-11eb-87e0-2f5f7f396dc8.png)
