### ISSUE TITLE
map2: when reaching maxzoom, dont shift the map anymore

### ISSUE THREAD

**Issue by telemaxx** [wolfgang-ch/mytourbook#370]
my current setting:

![grafik](https://user-images.githubusercontent.com/22706487/127169323-f7455b3c-0b72-490b-a463-13c179289bf2.png)

when i now click "zoom in" the map is zoomed and the "mouse position" is shiftet to the center. 
when i reached the max zoomlevel, the map is still shifting. this is confusing to me.

the 2nd best solution would be for me:
shifting and zooming until max zoomlevel, than dont zoom and dont shift anymore.

best solution would be:
like above, but dont move the mouseposition to the windowcenter, instead the mapposition below the mousepointer should stay the at the mouse position.
i think, there was already a FR for that...

**Comment by FJBDev** [comment]
>> when i reached the max zoomlevel, the map is still shifting. this i confusing to me 

I have always had the same confusion. I think it should not shift anymore. When I try on Google Maps, when I zoom to the max, it doesn't shift. 


De: "Thomas Th." ***@***.***> 
À: "wolfgang-ch/mytourbook" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 27 Juillet 2021 14:23:17 
Objet: [wolfgang-ch/mytourbook] map2: when reaching maxzoom, dont shift the map anymore (#370) 





my current setting: 

[ https://user-images.githubusercontent.com/22706487/127169323-f7455b3c-0b72-490b-a463-13c179289bf2.png ] 


when i now click "zoom in" the map is zoomed and the "mouse position" is shiftet to the center. 
when i reached the max zoomlevel, the map is still shifting. this i confusing to me. 

the 2nd best solution would be for me: 
shifting and zooming until max zoomlevel, than dont zoom and dont shift anymore. 

best solution would be: 
like above, but dont move the mouseposition to the windowcenter, instead the mapposition below the mousepointer should stay the at the mouse position. 
i think, there was already a FR for that...

**Comment by wolfgang-ch** [comment]
>when i reached the max zoomlevel, the map is still shifting

because the mouse is not in the center of the map, so functional it is correct. When you position the mouse in the center of the map then it do not shift but I'll "fix" this issue

**Comment by wolfgang-ch** [comment]
This was already "fixed" but then another behavior didn't work

https://github.com/wolfgang-ch/mytourbook/blob/2b7e33fa11f3f13176adea6b0a927d3eceb0f690/bundles/net.tourbook/src/de/byteholder/geoclipse/map/Map.java#L6369-L6373
