### ISSUE TITLE
Show battery voltage

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#376]
A .fit file contains data which are not yet displayed in MT, e.g. the battery voltage of the attached sonsors where a battery replacement can be detected.

![image](https://user-images.githubusercontent.com/1283445/128625203-bc3d83d3-51e8-480a-b30b-41f5654bdab3.png)

**Comment by FJBDev** [comment]
That could be a very useful feature!

**Comment by wolfgang-ch** [comment]
The above battery voltages are available only for the sensors but not for the recording device, e.g. Garmin Edge 1030.

In the "Fit File Tools" I saw, that the battery percentage is available somewhere in the fit data and because this tool shows the exact timeline location, I could find the fit value for the battery percentage.

![fit file tool](https://user-images.githubusercontent.com/1283445/128973767-c34e035f-b8a0-47bb-b947-be5882c30eae.png)

![image](https://user-images.githubusercontent.com/1283445/128973780-7576e80a-8eda-4526-bbc7-640ede468fe7.png)

**Comment by FJBDev** [comment]
> The above battery voltages are available only for the sensors but not for the recording device, e.g. Garmin Edge 1030.
> 

When I read the documentation of the [Fit File Tool](https://www.microsoft.com/en-us/p/fit-file-tools/9nj8rzgjnxdf?activetab=pivot:overviewtab), I read that there could be the battery status of the GPS device:

Battery; Display of the energy consumption of the **GPS device** and the energy status of the coupled devices.

**Comment by wolfgang-ch** [comment]
I found mesgNum == 104 contains the device battery values

![image](https://user-images.githubusercontent.com/1283445/129056881-c54a7628-de07-45e5-842a-a0134aa75b19.png)

**Comment by FJBDev** [comment]
In the FIT SDK, there is a `getBatterySoc()` function but I am not sure if it's for the device or the a sensor

https://github.com/dgaff/fitsdk/blob/7f38d911388b7cdc3db7bf0318239352928faa8b/java/com/garmin/fit/RecordMesg.java#L1319

**Comment by wolfgang-ch** [comment]
I already saw, there is a battery soc field but this is not contained in the .fit file, going with mesgNum = 104 is OK

**Comment by wolfgang-ch** [comment]
These are the battery values from a 5h tour, Value 3 is the % value but have no idea about the other 3 values, maybe when I see these values in other tours then we may also keep them

![image](https://user-images.githubusercontent.com/1283445/129066632-097a040d-98a3-4c54-a2e6-cbbb7ec6385f.png)

**Comment by FJBDev** [comment]
> maybe when I see these values in other tours then we may also keep them
> 

You can try to use my FIT files that are used in the [unit tests](https://github.com/wolfgang-ch/mytourbook/tree/main/bundles/net.tourbook.tests/test/importdata/garmin/fit/files)

**Comment by wolfgang-ch** [comment]
Show battery SoC in the statistics

![image](https://user-images.githubusercontent.com/1283445/129374840-101fa502-1243-4aa4-a5db-4b33d5d68ae5.png)

**Comment by wolfgang-ch** [comment]
After having so much battery data, the question occures if we could see the long term battery performance. 

When calculating the battery performance with this formula

![image](https://user-images.githubusercontent.com/1283445/129438175-a35fe148-d211-4186-a1ab-cdcaefd665e1.png)

and ignoring low battery diff values, there is no satisfiying graph

`batteryDiff < 1`
![battery diff 1](https://user-images.githubusercontent.com/1283445/129438228-bcb3bee7-db0d-4128-8760-3eafda75b04b.png)

`batteryDiff < 10`
![battery diff 10](https://user-images.githubusercontent.com/1283445/129438233-d43463a6-08f8-4e5c-b64e-7b9f672ef620.png)

`batteryDiff < 20`
![battery diff 20](https://user-images.githubusercontent.com/1283445/129438240-8febe8f0-6b37-4e36-8e59-22a3d430a5eb.png)

`batteryDiff < 30`
![battery diff 30](https://user-images.githubusercontent.com/1283445/129438243-4e74177b-d924-4da5-9b9a-368a32bb380c.png)

`batteryDiff < 40`
![battery diff below 40](https://user-images.githubusercontent.com/1283445/129438245-a0065013-413a-4a99-b78a-3e81d410c737.png)

There is another battery value additional to the percentage value, it looks like the battery voltage which is about factor 100 higher (~3000 - ~4500, it has 2 more digits) but there is no much better and useful graph

**Comment by wolfgang-ch** [comment]
A first glimpse on the sensor battery values, e.g. heart rate, speed or cadence.

The x-axis shows the numer of tours, multiplied by 2 because for each tour there is a start and end value but sometimes there is only a start or an end value. Missing values are not displayed.

![sonsor id 2](https://user-images.githubusercontent.com/1283445/135867604-bbbbd690-55ad-4cee-ac87-7fe562cfda93.png)

![sonsor id 4](https://user-images.githubusercontent.com/1283445/135867611-241d816c-ff57-4c78-8555-075216f284df.png)

![sonsor id 6](https://user-images.githubusercontent.com/1283445/135867614-3da1b9cf-0c93-4955-a053-7f9dae83a9ac.png)

![sonsor id 7](https://user-images.githubusercontent.com/1283445/135867616-f4402722-ce23-4c84-9c0c-1927ef787607.png)

**Comment by wolfgang-ch** [comment]
>Does Garmin support it for all their devices ?

No, only 5 of my Garmin devices has these sensor data

Since yesterday there is a new UI :-)

![image](https://user-images.githubusercontent.com/1283445/136325615-43d8a1a4-b458-430c-b375-947d4a63d8c8.png)

**Comment by wolfgang-ch** [comment]
There are similar phases in a battery life cycle 

* Red - First usage
* Blue - Increasing voltage 
* Green - Declining voltage

A pink line is from the voltage start to the voltage end during a tour

![image](https://user-images.githubusercontent.com/1283445/136688451-5a363ca3-a3c1-45df-b11d-9647182edd47.png)

**Comment by wolfgang-ch** [comment]
You have to delete the tour db and reimport the battery values again (which is now very fast :-) and the reason why I also implemented it before continuing the battery feature). 

The db structure is not final and can/will change when needed.

**Comment by telemaxx** [comment]
> however too few data to be useful for battery sensor testing

i can do some tests, i have this sensors:

- Cad from Wahoo and Magene
- Speed from Wahoo and Magene
- Garmin Radar

As recording devices i have garmins and fitfiles from oruxmaps(android)

**Comment by FJBDev** [comment]
I tried today this sensor feature and I have observations.
I started from a fresh empty database after i found FIT files from users that contain sensor information.

When I import and save the files, the sensors are not displayed
![image](https://user-images.githubusercontent.com/25235665/137064528-6be28a19-93b7-4e2c-a455-b5c9dab0a7d1.png)

Only when I restart MT, the sensors are displayed is that normal?
![image](https://user-images.githubusercontent.com/25235665/137064569-56b37332-d5d5-4b29-b983-899d85fdcc70.png)

Unfortunately, those sensors appears not to have battery data

**Comment by wolfgang-ch** [comment]
>When I import and save the files, the sensors are not displayed

After a re-import the sensor view is updated, not yet after a new import

>Only when I restart MT, the sensors are displayed is that normal?

Just close and reopen the sensor view, then the data are loaded again

**Comment by wolfgang-ch** [comment]
> > When I import and save the files, the sensors are not displayed
> 
> After a re-import the sensor view is updated, not yet after a new import

Fixed in https://github.com/wolfgang-ch/mytourbook/commit/a04cd84fcc3d6d291452deeb4ccc3e74874cce7b

**Comment by wolfgang-ch** [comment]
The cadence battery lasts a very long time down to a very low voltage but then the sensor do not send data any more

![image](https://user-images.githubusercontent.com/1283445/137276124-efc66b50-048e-4e5e-b9a4-651bfd2bde3d.png)

**Comment by wolfgang-ch** [comment]
The bottom graph shows the difference of the battery currency between tour start and tour end which is divided by the tour duration, however this graph do now show something that is valuable. My thought was that the health of the battery could be displayed but this depends propably also on other parameters, e.g. temperature.

![image](https://user-images.githubusercontent.com/1283445/137506431-f66f4b2b-cf77-444c-8884-334cbdcccced.png)

**Comment by wolfgang-ch** [comment]
All `..._start` and `..._end` values which are not -1 are available in the fit file, the `..._end` values are set when a second event is fired at the end of the tour.

So one sensor value event is available in the fit file but not with very exciting data

The battery_level values are very new and not yet available in the current Fit SDK, I got it with this hint https://forums.garmin.com/developer/fit-sdk/f/discussion/276245/di2-battery-level and I had to update the firmware of my Edge 1030 to save these values into the fit file

![image](https://user-images.githubusercontent.com/1283445/139520594-6d0c1949-b1f5-4c07-9901-143579269b39.png)

**Comment by wolfgang-ch** [comment]
> 
> 
> Also, when I try to display the tour tooltip from the tourchart, I get this exception:
> 
> ```
> !ENTRY org.eclipse.ui 4 0 2021-10-29 16:31:58.950
> !MESSAGE Unhandled event loop exception
> !STACK 0
> java.lang.NullPointerException
> 	at net.tourbook.tour.TourInfoUI.updateUI_SensorValues(TourInfoUI.java:1890)
> 	at net.tourbook.tour.TourInfoUI.updateUI(TourInfoUI.java:1798)
> ```

This happened for all tours which had no sensor values, so I had not tested the "simple" tours :-)

This is now fixed and the tour info UI was more improved to show the sensor value chart when a sensor value is clicked, the battery SoC link is WIP

![image](https://user-images.githubusercontent.com/1283445/139541668-e936d61f-a6aa-49a2-895c-bae2b9d0fdbf.png)

**Comment by wolfgang-ch** [comment]
Done, maybe the sensor type list must be updated with additional sensor types, but sensor types are currently only informational and sortable in the sensor list
