### ISSUE TITLE
Re-import dialog is a bit confusing

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#378]
I just discovered by trying to add the re-import device sensor values, that the red marked fields are enabled when "All time slice..." is enabled. I think the red marked fields are tour fields and not time slice fields.

A solution which I see is to create a new checkbox "Tour data" which contains the red marked fields

![image](https://user-images.githubusercontent.com/1283445/128842135-b9a7b360-bbb0-4940-8bf8-ce91f8b7711d.png)

https://github.com/wolfgang-ch/mytourbook/blob/6cbbffbd1e7103c12593900e6c84d89ed2b4ec25/bundles/net.tourbook/src/net/tourbook/ui/views/rawData/DialogReimportTours.java#L65

**Comment by FJBDev** [comment]
We could create different sections "Time slices" and "Tour Data" but wouldn't it be confusing for the user ? "Time Slices" maybe is too similar to "Tour Data" for a user ?

**Comment by wolfgang-ch** [comment]
The current "header" text "All time slide data..." is just wrong for "Calories", "Tour markers" and "Import file location", these are not time slice data

**Comment by FJBDev** [comment]
Maybe the current header should be renamed to "All tour data" ?

**Comment by wolfgang-ch** [comment]
The "Tour Editor" has already this distinction

![image](https://user-images.githubusercontent.com/1283445/129047549-4ef7269c-03ef-418b-b9d4-7e7c9e868f82.png)

**Comment by wolfgang-ch** [comment]
**Old**
![image](https://user-images.githubusercontent.com/1283445/128842135-b9a7b360-bbb0-4940-8bf8-ce91f8b7711d.png)

**New**
![image](https://user-images.githubusercontent.com/1283445/129218024-52becb67-2ee7-46dd-adda-51a8dd9c59d3.png)
