### ISSUE TITLE
Automatic conversion of waypoints to markings doesn't work as expected (gpx import)

### ISSUE THREAD

**Issue by b-misc** [wolfgang-ch/mytourbook#390]
Hi

When importing gpx files, I set the option "Wegpunkte in Markierungen umwandeln".

I just imported a file, and some waypoints have been converted, as others have not. By looking into the gpx file, I didn't see any differences in two of these waypoints. Please see the attached file 
[bugreport.gpx.txt](https://github.com/wolfgang-ch/mytourbook/files/7115728/bugreport.gpx.txt)
.

- "Angélique möchte unbedingt wieder laufen " gets converted to a marking
- "Akuter Wickelstop für Angélique" gets imported as a waypoint, not converted to a marking

I'd expect all waypoints to get converted to markings.

Version is 21.6.1, OS Debian Linux

**Comment by wolfgang-ch** [comment]
Expanded geo diff and time diff to not skip waypoints when converted into tour markers

![image](https://user-images.githubusercontent.com/1283445/132455141-b1a68717-704e-4e2d-8afa-bd3d7d1abd47.png)
