### ISSUE TITLE
JUnit Test tries to download SRTM data but is not authorized

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#392]
Because the JUnit tests are 100% OK without SRTM data, is there a need that the tests are downloading SRTM data ?

When SRTM download is not authorized, these test are running into timeouts which delays the tests significantly.

```
java.lang.Exception: Response from server - 401: Unauthorized
	at net.tourbook.srtm.download.DownloadSRTM3.getResource(DownloadSRTM3.java:158)
	at net.tourbook.srtm.download.DownloadSRTM3$SRTM3_HTTPDownloader.getInputStream(DownloadSRTM3.java:68)
	at net.tourbook.srtm.download.HTTPDownloader$2.run(HTTPDownloader.java:98)
```

I've no idea, why `TourData.getSRTMSerie()` is called

```
Thread [main] (Suspended (breakpoint at line 8578 in TourData))	
	owns: RunnableLock  (id=159)	
	TourData.getSRTMSerie() line: 8578	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method] [local variables unavailable]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 566	
	BeanPropertyWriter.serializeAsField(Object, JsonGenerator, SerializerProvider) line: 689	
	BeanSerializer(BeanSerializerBase).serializeFields(Object, JsonGenerator, SerializerProvider) line: 770	
	BeanSerializer(BeanSerializerBase)._serializeWithObjectId(Object, JsonGenerator, SerializerProvider, boolean) line: 682	
	BeanSerializer.serialize(Object, JsonGenerator, SerializerProvider) line: 171	
	DefaultSerializerProvider$Impl(DefaultSerializerProvider)._serialize(JsonGenerator, Object, JsonSerializer<Object>) line: 480	
	DefaultSerializerProvider$Impl(DefaultSerializerProvider).serializeValue(JsonGenerator, Object) line: 319	
	ObjectWriter$Prefetch.serialize(JsonGenerator, Object, DefaultSerializerProvider) line: 1514	
	ObjectWriter._writeValueAndClose(JsonGenerator, Object) line: 1215	
	ObjectWriter.writeValueAsString(Object) line: 1085	
	TourData.toJson() line: 11328	
	Comparison.compareTourDataAgainstControl(TourData, String) line: 58	
	Suunto9Tester.testImportRRData() line: 147	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 566	
```

**Comment by FJBDev** [comment]
Yes, we could disable the SRTM data download since it requires now a token.


> I've no idea, why `TourData.getSRTMSerie()` is called

Maybe by default the code calls it ? Is it easy to disable it for the unit tests ?

**Comment by FJBDev** [comment]
In this [commit](https://github.com/wolfgang-ch/mytourbook/commit/6c51f636aba5240446e04cfd72d4438bde825d0f#diff-0b085fe6313e8f96920a44c64146cf9d5289f1b298c7e9854a08b79824171c28), I had updated the unit tests when SRTM needed a login/token but I didn't know if I could disable the SRTM download attempt without too much code rework.
```

Updating the unit tests as we now need to authenticate in order to
retrieve the srtm data
```

**Comment by wolfgang-ch** [comment]
> 
> 
> Yes, we could disable the SRTM data download since it requires now a token.
> 
> > I've no idea, why `TourData.getSRTMSerie()` is called
> 
> Maybe by default the code calls it ? Is it easy to disable it for the unit tests ?

All code between...

```
	TourData.getSRTMSerie() line: 8578	
        
             ...

	TourData.toJson() line: 11328	
```

...is from the framework you are using to create json data from TourData. 

Maybe there is an option in this framework to prevent calling getSRTMSerie() ?

**Comment by FJBDev** [comment]
You mean this [getSRTMSerie() call](https://github.com/wolfgang-ch/mytourbook/blob/295c0c16cded86164a4aa3413b18e4b3bbbd5be6/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L9753) ?

**Comment by wolfgang-ch** [comment]
`TourData.getSRTMSerie()` is called from line 5 somewhere in the framework

![image](https://user-images.githubusercontent.com/1283445/133025987-a1b476ba-2a3e-4d07-9d90-eb37ca7ed201.png)

**Comment by FJBDev** [comment]
@wolfgang-ch 
Fixed in this [PR ](https://github.com/wolfgang-ch/mytourbook/pull/394)and specifically in this commit [6c63028](https://github.com/wolfgang-ch/mytourbook/pull/394/commits/6c6302868d2316063d318ee7ca6839f952bc8dde)

**Comment by wolfgang-ch** [comment]
A copy of this commit is now merged into main https://github.com/wolfgang-ch/mytourbook/commit/fd765709aa4ed85ecade1fae02c890a1315b8115
