### ISSUE TITLE
A selected tour pause in the tour chart do not select the correct time slice in the tour editor

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#399]
When selecting 0:13 in the tour chart, then the time slice 2906 is selected instead of 2923. 

Selection do only work when the tour editor has the focus, otherwise it do not select the time slice.

When selecting a tour marker in the tour chart, then the correct time slice is selected in the tour editor, this also works when the tour editor has not the focus. 

![image](https://user-images.githubusercontent.com/1283445/134459611-869c357b-206e-4271-9102-0bfb58e74cbc.png)

**Comment by FJBDev** [comment]
Good find, I will investigate that.

**Comment by wolfgang-ch** [comment]
Now when selecting a pause in the chart, the correct time slice is selected according to the `Start Time` but it is irritating because when you select the 0:13 pause, then the time slice before 13 is selected in the tour editor. 

Currently I don't see a solution how to get this less irritating.

This is the current situation:

* The tour editor shows the time difference to the previous time slice 
* Tour chart show the pause time before the time gap

**Comment by FJBDev** [comment]
> 
> 
> Now when selecting a pause in the chart, the correct time slice is selected according to the `Start Time` but it is irritating because when you select the 0:13 pause, then the time slice before 13 is selected in the tour editor.
> 
> Currently I don't see a solution how to get this less irritating.
> 
> This is the current situation:
> 
>     * The tour editor shows the time difference to the previous time slice
> 
>     * Tour chart show the pause time before the time gap

I don't understand fully. Can you add a screenshot to illustrate what is irritating ?

**Comment by wolfgang-ch** [comment]
When you select the 0:19 pause in the chart, then the time slice 3363 is selected but the time slice with 19 sec time difference, is the next, 3364. When you select 3364 in the tour editor, then 2 sliders in the chart are positioned, the start and the end

![image](https://user-images.githubusercontent.com/1283445/134759961-9c0f8e9c-5df2-4b9d-8fe5-931f829bc296.png)

**Comment by FJBDev** [comment]
See my fix for it [here](https://github.com/wolfgang-ch/mytourbook/pull/402)
