### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by baimafeima** [wolfgang-ch/mytourbook#4]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by wolfgang-ch** [comment]
Currently issues are managed not in GitHub, they are in https://sourceforge.net/p/mytourbook/_list/tickets

I just created a readme.md for this project which also has a link to the release notes files. Each file contains all changes when a new version is published
