### ISSUE TITLE
[Cloud] Remove cloud accounts

### ISSUE THREAD

**Issue by wolfgang-ch** [wolfgang-ch/mytourbook#421]
All cloud accounts can be authorized in MT but they cannot be removed/cleanedup in the UI

**Comment by FJBDev** [comment]
> All cloud accounts can be authorized in MT but they cannot be removed/cleanedup in the UI

By "removed/cleaned up", you mean revoked ?

**Comment by FJBDev** [comment]
For example, in Strava, you can revoke the application access by going [here](https://www.strava.com/settings/apps) and clicking on "Revoke Access".

Maybe I can put a link to [this page](https://www.strava.com/settings/apps) in the Strava preference page ?

![image](https://user-images.githubusercontent.com/25235665/142730532-7bb214f0-b0c6-4197-9b0c-0c73dabfbc58.png)

**Comment by wolfgang-ch** [comment]
> > All cloud accounts can be authorized in MT but they cannot be removed/cleanedup in the UI
> 
> By "removed/cleaned up", you mean revoked ?

Just to cleanup the account in MT which would be also useful for testing it and which is the reason why I missed it. Some features in MT are mainly available to make testing and many restestings easier, e.g. repositioned windows/slideouts

**Comment by wolfgang-ch** [comment]
> Maybe I can put a link to this page in the Strava preference page ?

This is a good idea !

**Comment by FJBDev** [comment]
> > > All cloud accounts can be authorized in MT but they cannot be removed/cleanedup in the UI
> > 
> > 
> > By "removed/cleaned up", you mean revoked ?
> 
> Just to cleanup the account in MT which would be also useful for testing it and which is the reason why I missed it. Some features in MT are mainly available to make testing and many restestings easier, e.g. repositioned windows/slideouts

If you click on "Restore defaults", it will clean up the cloud account in MT, did you try?

**Comment by wolfgang-ch** [comment]
> > > > All cloud accounts can be authorized in MT but they cannot be removed/cleanedup in the UI
> > > 
> > > 
> > > By "removed/cleaned up", you mean revoked ?
> > 
> > 
> > Just to cleanup the account in MT which would be also useful for testing it and which is the reason why I missed it. Some features in MT are mainly available to make testing and many restestings easier, e.g. repositioned windows/slideouts
> 
> If you click on "Restore defaults", it will clean up the cloud account in MT, did you try?

No, I didn't expect this feature in this button.

I would disable the default/apply button with `org.eclipse.jface.preference.PreferencePage.noDefaultAndApplyButton()` which is already done in some other pref pages and provide a cleanup button

**Comment by FJBDev** [comment]
> I would disable the default/apply button with `org.eclipse.jface.preference.PreferencePage.noDefaultAndApplyButton()` which is already done in some other pref pages and provide a cleanup button

But I need an "Apply" button to save the cloud information (token)

**Comment by wolfgang-ch** [comment]
> > I would disable the default/apply button with `org.eclipse.jface.preference.PreferencePage.noDefaultAndApplyButton()` which is already done in some other pref pages and provide a cleanup button
> 
> But I need an "Apply" button to save the cloud information (token)

There is an "Apply and Close" button and combined with `de.byteholder.geoclipse.preferences.PrefPage_Map2_Providers.okToLeave()` you could also save the cloud info. 

There is currently no consistent concept how to deal with `OK` and `Close` buttons in pref pages however I introduced the `Live update` checkbox, in slideouts all modifications are applied also immediately

**Comment by FJBDev** [comment]
> > > I would disable the default/apply button with `org.eclipse.jface.preference.PreferencePage.noDefaultAndApplyButton()` which is already done in some other pref pages and provide a cleanup button
> > 
> > 
> > But I need an "Apply" button to save the cloud information (token)
> 
> There is an "Apply and Close" button and combined with `de.byteholder.geoclipse.preferences.PrefPage_Map2_Providers.okToLeave()` you could also save the cloud info.
> 
> There is currently no consistent concept how to deal with `OK` and `Close` buttons in pref pages however I introduced the `Live update` checkbox, in slideouts all modifications are applied also immediately

Fixed in my [PR](https://github.com/wolfgang-ch/mytourbook/pull/423)
