### ISSUE TITLE
Cannot run MyTourbook in Eclipse, rest see Forum.

### ISSUE THREAD

**Issue by telemaxx** [wolfgang-ch/mytourbook#7]
![01_git_1](https://user-images.githubusercontent.com/22706487/47253001-c22b7b80-d44d-11e8-91c5-6b2f152055b8.PNG)
![02_git_2](https://user-images.githubusercontent.com/22706487/47253003-c48dd580-d44d-11e8-879b-59fb4427d31c.PNG)
![03_git_3](https://user-images.githubusercontent.com/22706487/47253004-c6579900-d44d-11e8-971a-32c05df9304b.PNG)
![04_git_import_1](https://user-images.githubusercontent.com/22706487/47253005-c8215c80-d44d-11e8-851e-b1e4840a22b0.PNG)
![05_git_import_de byteholder](https://user-images.githubusercontent.com/22706487/47253006-c9eb2000-d44d-11e8-8ee9-d10509af7559.PNG)
![06_git_import_net tourbook](https://user-images.githubusercontent.com/22706487/47253007-cb1c4d00-d44d-11e8-94bd-ffe312aad99b.PNG)
![07_git_import_org apache](https://user-images.githubusercontent.com/22706487/47253009-cc4d7a00-d44d-11e8-988c-ec248933c0e1.PNG)
![08_git_import_gradle_error1](https://user-images.githubusercontent.com/22706487/47253011-ce173d80-d44d-11e8-8be2-28bc14cf646e.PNG)
![09_run_config_tab1](https://user-images.githubusercontent.com/22706487/47253013-cf486a80-d44d-11e8-827f-6e3e3c66a9dc.PNG)
![10_run_config_tab2](https://user-images.githubusercontent.com/22706487/47253016-d0799780-d44d-11e8-86d0-77fb54d85094.PNG)
![11_run_config_tab3](https://user-images.githubusercontent.com/22706487/47253017-d2435b00-d44d-11e8-8051-f5ddec04a582.PNG)
![11_run_config_tab3validate](https://user-images.githubusercontent.com/22706487/47253018-d40d1e80-d44d-11e8-9ca5-e673d670af54.PNG)
![11_run_config_tab4](https://user-images.githubusercontent.com/22706487/47253019-d66f7880-d44d-11e8-804c-b2ea55d0c781.PNG)
![11_run_config_tab7](https://user-images.githubusercontent.com/22706487/47253021-d8393c00-d44d-11e8-9f58-8772a9a3a881.PNG)
![12_running1](https://user-images.githubusercontent.com/22706487/47253056-83e28c00-d44e-11e8-8ccd-ed87d644f4c9.PNG)
![12_running2](https://user-images.githubusercontent.com/22706487/47253057-85ac4f80-d44e-11e8-8ec3-cd1c3945c09b.PNG)
![13_running3](https://user-images.githubusercontent.com/22706487/47253059-87761300-d44e-11e8-9b4f-7c10eb04d679.PNG)

**Comment by telemaxx** [comment]
https://sourceforge.net/p/mytourbook/discussion/622811/thread/d2e504231e/?limit=25#2645

**Comment by wolfgang-ch** [comment]
solved see above link
