### ISSUE TITLE
Graphs don't check whether to show cadence or revolutions

### ISSUE THREAD

**Issue by tesseract241** [wolfgang-ch/mytourbook#86]
When hovering over a graph, data appears referring to the point in the graph the mouse is on: this data does not take into account whether the track has been saved as a using cadence or revolutions, and always shows revolutions.

**Comment by wolfgang-ch** [comment]
I've put this into the todo list for next version https://github.com/wolfgang-ch/mytourbook/blob/master/info/release-notes/19.9.0-readme.txt#L11-L13
